<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-LBN8TGD" ignored="0" name="Test(failed)" tests="2" failures="2" timestamp="29 Mar 2019 12:06:59 GMT" time="0.035" errors="0">
  <testcase name="run" time="0.008" classname="testng.TestRetry1">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testng.TestRetry1.run(TestRetry1.java:11)
at testng.MultiRetry.main(MultiRetry.java:15)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- run -->
  <testcase name="run" time="0.001" classname="testng.TestRetry2">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testng.TestRetry2.run(TestRetry2.java:10)
at testng.MultiRetry.main(MultiRetry.java:15)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- run -->
</testsuite> <!-- Test(failed) -->
